POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Touni Testicle",
    "number": "050 111 4444"
}
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Ar",
    "number": "040 123 4567"
}